#!/usr/bin/env python3
"""Build the single PDF that PLOS ONE's format-free initial submission wants.

  "PLOS ONE waives all formatting requirements until your manuscript has
   received a provisional Editorial Accept decision."  -- getting-started page

so what is uploaded is one PDF containing the text and the figures. This builds
it from the Markdown source rather than from a hand-maintained second copy,
because a manuscript that exists twice drifts, and this project has already paid
for one drift.

Three things it does that a plain `pandoc paper.md -o paper.pdf` does not:

  * embeds the figures. The manuscript's §Figures is a list of captions naming
    image stems, which is right for a repository and useless in a submission;
    each entry becomes the actual figure with its caption beneath.
  * adds the title page PLOS expects, with the affiliation and ORCID left as
    visible placeholders. A made-up affiliation on a submitted manuscript is
    worse than an obvious gap.
  * uses XeLaTeX and a font with Greek and combining marks, because the paper
    prints beta, tau, theta-hat, superscript nine and subscript zero, and
    pdflatex silently drops what it cannot set.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import unicodedata
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "docs" / "PAPER_DRAFT_v2.md"
FIGDIR = ROOT / "docs" / "figures"
BUILD = ROOT / "build" / "submission"
OUT = BUILD / "PLOS_ONE_submission.pdf"
SUPP = ROOT / "docs" / "PAPER_SUPPLEMENT_v1.md"
SUPP_OUT = BUILD / "PLOS_ONE_supplement.pdf"

AUTHOR = "Ali Çetinkaya"
# Affiliation as the author records it elsewhere in his own materials; the
# ORCID is filled by tools/fill_orcid.py from the public registry when a single
# unambiguous match exists, and is otherwise left as a bracket the guard sees.
AFFIL = ("Department of Computer Engineering, Faculty of Technology, Selçuk "
         "University, Konya, Türkiye")
ORCID = "[ORCID — to be completed before submission]"

# Fonts are tried in order; the first one fontspec can load wins. Times New Roman
# and Helvetica ship with macOS; the two Latin Modern entries are the TeX
# fallbacks so the build still runs on a machine without them.
FONT_CANDIDATES = ["TeX Gyre Termes", "Charter", "Georgia",
                   "Latin Modern Roman", "Times New Roman"]
# The model equation is written in a code span, so it is set in the MONO font,
# and the default (Latin Modern Mono) has no Greek. That silently deleted the
# three coefficients from the one line that defines the estimand:
#   "log E[count_it] = year FE + γ·WB + τ·(WB × centred year) + β·(WB × post)"
# became "= year FE + ·WB + ·(WB × centred year) + ·(WB × post)".
ARROW = "\u2192"
MONO_CANDIDATES = ["Menlo", "DejaVu Sans Mono", "Courier New", "Latin Modern Mono"]

SUPER = {"⁰": "0", "¹": "1", "²": "2", "³": "3", "⁴": "4",
         "⁵": "5", "⁶": "6", "⁷": "7", "⁸": "8", "⁹": "9"}
SUB = {"₀": "0", "₁": "1", "₂": "2", "₃": "3", "₄": "4",
       "₅": "5", "₆": "6", "₇": "7", "₈": "8", "₉": "9"}


def scripts_to_math(md: str) -> str:
    """Rewrite Unicode super/subscripts as LaTeX math.

    Times New Roman on macOS has no glyph for U+2079, so "2⁹ = 512" set with it
    silently becomes "2 = 512" — a claim about the bootstrap's support turning
    into an arithmetic falsehood, with no error anywhere in the build. The first
    version of this script shipped that PDF. LaTeX math needs no font coverage,
    so the substitution removes the dependency instead of hoping for it.
    """
    md = re.sub("[" + "".join(SUPER) + "]+",
                lambda m: "$^{" + "".join(SUPER[c] for c in m.group(0)) + "}$", md)
    md = re.sub("[" + "".join(SUB) + "]+",
                lambda m: "$_{" + "".join(SUB[c] for c in m.group(0)) + "}$", md)
    # Same device for the arrow. Every era contrast in the manuscript is written
    # "39.96 → 22.97", and the serif faces whose text layer records punctuation
    # correctly do not all carry U+2192. Setting it as maths removes the
    # dependency rather than constraining the font choice to fonts that have it.
    md = md.replace(ARROW, "$\\rightarrow$")
    return md


def embed_figures(md: str) -> str:
    """Turn each inline caption paragraph into a real figure.

    PLOS wants the caption placed after the paragraph that first cites the
    figure, so the captions no longer live in a section of their own. Each
    caption paragraph reads

        **Fig 1. Title.** <legend> (`fig1_composition`; regenerated by
        `tools/make_paper_figures.py`.)

    and the image is placed immediately above it, where it stands.
    """
    pat = re.compile(r"^\*\*Fig (\d+)\. ([^*]+?)\*\* (.*?)\(`([a-z0-9_]+)`[;,][^)]*\)\s*$",
                     re.S | re.M)
    entries = pat.findall(md)
    if not entries:
        raise SystemExit("[pdf] refusing: matched no caption entries of the form "
                         "'**Fig N. Title.** legend (`stem`; ...)'")

    def one(m):
        num, title, legend, stem = m.groups()
        src = FIGDIR / f"{stem}.pdf"
        if not src.exists():
            src = FIGDIR / f"{stem}.png"
        if not src.exists():
            raise SystemExit(f"[pdf] refusing: no image for {stem} in {FIGDIR}")
        legend = " ".join(legend.split())
        return (f"![]({src}){{width=95%}}\n\n"
                f"**Fig {num}. {title.strip()}** {legend}")
    return pat.sub(one, md)


def title_page(md: str) -> tuple[str, str]:
    """Split the H1 off and return (title, rest)."""
    first, rest = md.split("\n", 1)
    return first.lstrip("# ").strip(), rest


def probe_font(name: str, setter: str, sample: str) -> bool:
    """True if xelatex can load the font AND set every sample character in it.

    Loading is not coverage: xelatex loads Latin Modern Mono happily and then
    writes notdefs for Greek. So the probe renders the sample and reads the
    result back, which is the only check that answers the question asked.
    """
    probe = BUILD / "fontprobe.tex"
    # The sample has to be typeset IN the font under test. Setting monofont and
    # then writing the sample as body text measures the main font instead, which
    # is what the first version did: every mono candidate "failed" because the
    # probe never used one.
    body = f"\\texttt{{{sample}}}" if setter == "setmonofont" else sample
    probe.write_text("\\documentclass{article}\\usepackage{fontspec}"
                     f"\\{setter}{{{name}}}\\pagestyle{{empty}}"
                     f"\\begin{{document}}\\noindent {body}\\end{{document}}",
                     encoding="utf-8")
    (BUILD / "fontprobe.pdf").unlink(missing_ok=True)   # never read a stale probe
    r = subprocess.run(["xelatex", "-interaction=nonstopmode", "-halt-on-error",
                        probe.name], cwd=BUILD, capture_output=True)
    if r.returncode != 0:
        return False
    try:
        import fitz
    except ImportError:
        return True
    out = (BUILD / "fontprobe.pdf")
    if not out.exists():
        return False
    text = "".join(pg.get_text() for pg in fitz.open(out))
    if "\ufffd" in text or "\uffff" in text:
        return False
    # Drawing the right glyph is not the same as recording the right character.
    # macOS Times New Roman sets a perfectly ordinary semicolon and then maps it
    # in ToUnicode to U+037E GREEK QUESTION MARK, which is canonically
    # equivalent to U+003B and therefore invisible to a notdef scan and to any
    # reader who normalises. Every semicolon in both submission PDFs was U+037E
    # for eighteen rounds. So the probe now reads the sample back character by
    # character and rejects a font that changes one.
    for ch in sample:
        if ch.isspace():
            continue
        if ch not in text:
            return False
    return True


GREEK_SAMPLE = "β τ γ θ α σ δ π ≥ × − §"
# Ordinary punctuation, in the probe for the reason above: these are the
# characters a font is most likely to draw correctly and record wrongly.
# No quotes or apostrophes: LaTeX turns those into directional forms on
# purpose, so their absence would be a false failure rather than a font defect.
PUNCT_SAMPLE = "; : , . ( ) [ ] ? ! -"


def manuscript_sample() -> str:
    """Every non-ASCII character the two source documents actually contain.

    A hand-written sample tests what the author remembered. This tests what the
    manuscript holds, which is the only list that matters. It would have caught
    both of round 18's font defects: Charter has no U+2192 RIGHTWARDS ARROW and
    the manuscript uses it in every era contrast, and macOS Times New Roman
    records a semicolon as U+037E.
    """
    chars = set()
    for f in (PAPER, SUPP):
        if f.exists():
            chars |= {c for c in f.read_text(encoding="utf-8") if ord(c) > 127}
    chars -= {"\u201c", "\u201d", "\u2018", "\u2019"}   # LaTeX makes these itself
    chars -= set(SUPER) | set(SUB) | {ARROW}   # rewritten as maths before typesetting
    return " ".join(sorted(chars))


def pick_fonts() -> tuple[str, str]:
    sample = (GREEK_SAMPLE + " θ̂ " + PUNCT_SAMPLE + " "
              + manuscript_sample())
    main = next((f for f in FONT_CANDIDATES
                 if probe_font(f, "setmainfont", sample)), None)
    mono = next((f for f in MONO_CANDIDATES
                 if probe_font(f, "setmonofont", GREEK_SAMPLE)), None)
    if not main or not mono:
        raise SystemExit(f"[pdf] refusing: no usable font "
                         f"(main={main}, mono={mono}). The sample includes Greek "
                         "because the manuscript's estimand is written in it.")
    return main, mono


def main(supplement: bool = False) -> int:
    """Build the manuscript, or the supporting information, through one path.

    The supplement shipped as raw Markdown for seventeen rounds. PLOS publishes
    supporting information in the format it is given, so that would have gone
    out as a .md file with no typesetting and no font embedding — and, more to
    the point, with none of the glyph checking below, which is the only reason
    the manuscript's "2^9 = 512" and its Greek coefficients survived at all.
    The supplement is full of both. So it is built here rather than beside here.
    """
    if not shutil.which("xelatex") or not shutil.which("pandoc"):
        raise SystemExit("[pdf] needs pandoc and xelatex on PATH")
    BUILD.mkdir(parents=True, exist_ok=True)

    src_path, out_path = (SUPP, SUPP_OUT) if supplement else (PAPER, OUT)
    md = src_path.read_text(encoding="utf-8")
    if supplement:
        title = md.split("\n", 1)[0].lstrip("# ").strip()
        rest = md.split("\n", 1)[1]
    else:
        title, rest = title_page(embed_figures(md))
        # The front block (analysis-plan DOI, its sha256, the OSF id) is not
        # body text and carries a 64-hex hash that wraps. With line numbers
        # on, the text layer of the wrapped hash picked up the digit of the
        # line number beside the break, and a reader copying the hash would
        # copy 65 characters. Numbering starts at the abstract instead.
        if "## Abstract" in rest:
            rest = ("\\nolinenumbers\n\n" + rest.replace("## Abstract",
                                                       "\\linenumbers\n\n## Abstract", 1))
    font, mono = pick_fonts()
    print(f"[pdf] fonts: text {font}, code {mono}")

    header = (
        "---\n"
        f'title: "{title}"\n'
        f'author: "{AUTHOR}"\n'
        + ("" if supplement else f'date: "{AFFIL}\\\\newline {ORCID}"\n')
        +
        "geometry: margin=2.4cm\n"
        f'mainfont: "{font}"\n'
        f'monofont: "{mono}"\n'
        "monofontoptions: Scale=0.85\n"
        "fontsize: 11pt\n"
        # PLOS enforces double spacing on the manuscript file. pandoc applies
        # linestretch through setspace AFTER header-includes, so a
        # \\doublespacing placed there was silently overridden and a 38-page
        # build came out at 37. The variable is the one place that works.
        + ("linestretch: 1.15\n" if supplement else "linestretch: 2.0\n")
        +         "colorlinks: true\n"
        "urlcolor: black\n"
        "linkcolor: black\n"
        "header-includes:\n"
        # Five lines ran past the right edge of the page and the characters past
        # it were not drawn at all -- the title page printed 62 of the deposit's
        # 64 sha256 hex digits, and the last sentence of S10.8 stopped mid-word.
        # seqsplit lets a long path break anywhere rather than overrun; sloppy
        # and emergencystretch handle the prose lines. verify() now refuses if
        # anything still overflows.
        "  - \\usepackage{seqsplit}\n"
        "  - \\let\\origtexttt\\texttt\n"
        "  - \\renewcommand{\\texttt}[1]{\\origtexttt{\\seqsplit{#1}}}\n"
        "  - \\sloppy\n"
        "  - \\setlength{\\emergencystretch}{3em}\n"
        "  - \\usepackage{longtable}\n"
        "  - \\usepackage{booktabs}\n"
        "  - \\AtBeginEnvironment{longtable}{\\footnotesize}\n"
        "  - \\usepackage{etoolbox}\n"
        # PLOS ONE enforces these on the manuscript file at initial submission:
        # continuous line numbers, double spacing, page numbers. The supplement
        # is supporting information and is not held to them.
        + ("" if supplement else
           "  - \\usepackage{lineno}\n"
           "  - \\linenumbers\n")
        + "---\n\n"
    )
    # Pandoc reads ANY line of three dashes as the start of a YAML metadata
    # block, not just the one at the top, and this manuscript separates sections
    # with them. Left alone, pandoc tries to parse §2 as YAML and dies at line
    # 182 with a message that points at the header. `* * *` is an unambiguous
    # horizontal rule and renders identically.
    rest = re.sub(r"^---$", "* * *", rest, flags=re.M)
    rest = scripts_to_math(rest)
    src = BUILD / ("supplement.md" if supplement else "submission.md")
    src.write_text(header + rest, encoding="utf-8")

    # No --toc. A contents list on page one reads as a thesis or a technical
    # report rather than a journal article, and PLOS does not ask for one.
    # The PDF still carries a bookmark outline, which is navigation without
    # spending a page on it.
    cmd = ["pandoc", str(src), "-o", str(out_path), "--pdf-engine=xelatex",
           "--from", "markdown+pipe_tables+tex_math_dollars"]
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=BUILD)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("[pdf] pandoc failed")

    return verify(md, out_path, supplement)


def verify(source_md: str, out_path: Path = OUT,
           supplement: bool = False) -> int:
    """Read the built PDF back and refuse to call it done if a glyph is missing.

    XeLaTeX does not fail on a character the font cannot set; it writes a notdef,
    which extracts as U+FFFF and prints as nothing. So the only way to know the
    PDF says what the manuscript says is to read the PDF.
    """
    try:
        import fitz
    except ImportError:
        print("[pdf] WARNING: PyMuPDF not available, glyph check skipped")
        return 0

    doc = fitz.open(out_path)
    text = "".join(page.get_text() for page in doc)

    over = []
    for i, page in enumerate(doc, start=1):
        limit = page.rect.width - 1.0
        for blk in page.get_text("dict")["blocks"]:
            for line in blk.get("lines", []):
                if line["bbox"][2] > limit:
                    tail = "".join(sp["text"] for sp in line["spans"])[-60:]
                    over.append((i, line["bbox"][2], tail))
    if over:
        sys.stderr.write(f"[pdf] REFUSING: {len(over)} line(s) typeset past the "
                         "page edge; the characters past it are not drawn:\n")
        for i, x1, tail in over[:8]:
            sys.stderr.write(f"    p{i} x1={x1:.1f} ...{tail}\n")
        return 1

    # U+037E is canonically equivalent to a semicolon, so it survives a notdef
    # scan and a normalising reader, and is wrong in the text layer regardless.
    # pick_fonts should have excluded any font that does this; check the built
    # artifact anyway, because the probe tests a sample and this tests the page.
    strays = {c for c in text if unicodedata.normalize("NFC", c) != c}
    if strays:
        sys.stderr.write("[pdf] REFUSING: the text layer records characters "
                         "that are canonically equivalent to, but not, what the "
                         f"source holds: {sorted(hex(ord(c)) for c in strays)}\n")
        return 1

    bad = text.count("\ufffd") + text.count("\uffff")
    if bad:
        ctx = [text[max(0, i - 30):i + 30].replace("\n", " ")
               for i, c in enumerate(text) if c in "\ufffd\uffff"][:5]
        sys.stderr.write("[pdf] REFUSING: %d unrenderable glyph(s):\n" % bad)
        for c in ctx:
            sys.stderr.write(f"    ...{c}...\n")
        return 1

    # A spot check that the numbers actually survived typesetting, not just that
    # nothing errored. These are the load-bearing figures of the three results.
    # Load-bearing figures, per document: a spot check that the numbers
    # survived typesetting rather than that nothing errored.
    must = (["0.037", "0.086", "512", "24.4", "0.310", "S10.7", "S10.8"]
            if supplement else
            ["39.96", "22.97", "0.0142", "512", "0.16", "Fig 1.", "Fig 4."])
    missing = [m for m in must if m not in text]
    if missing:
        sys.stderr.write(f"[pdf] REFUSING: not in the built PDF: {missing}\n")
        return 1

    print(f"[pdf] wrote {out_path.relative_to(ROOT)}  "
          f"({out_path.stat().st_size/1024:.0f} KB, {doc.page_count} pages)")
    print(f"[pdf] glyph check clean; {len(must)} load-bearing strings present")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--supplement", action="store_true",
                    help="build the supporting information instead")
    ap.add_argument("--both", action="store_true")
    a = ap.parse_args()
    if a.both:
        sys.exit(main(False) or main(True))
    sys.exit(main(a.supplement))
