#!/usr/bin/env python3
"""Refuse if a table or figure generator reads a file the deposit does not carry.

The data-availability statement promises that "each numbered table and figure in
the manuscript is regenerated by a named command." A reader who unpacks the
deposit and runs those commands gets

    File "tools/make_paper_tables.py", line 112, in t1_corpus
        f"({tot['extracted']/tot['sampled']:.1%}), "
    ZeroDivisionError: division by zero

because five inputs the generators read are in no deposit list, and the readers
return [] for a missing path rather than complaining. The promise is false and
nothing measured it.

This does NOT decide what to deposit. Three of the five files carry IMF material
of different kinds and the include/exclude call is the author's, not a script's:

  data/meta/frozen_sampling_v2.csv   display_title, txturl and pdfurl for 1,064
                                     IMF documents -- verbatim bibliographic
                                     frame, which the permission forbids
                                     redistributing. Cannot be deposited whole.
  data/meta/ocr_log.csv              IMF report numbers in `id` and `path`.
  data/meta/extraction_log.csv       no IMF signature found, but the same shape.
  data/features/classic.csv          report-number ids plus numeric features
  data/features/family_counts.csv    only -- the same class as the already
                                     published imf_document_index.csv.

What it does is make the gap loud, so the decision is taken deliberately instead
of discovered by a referee running the command.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATORS = ["tools/make_paper_tables.py", "tools/make_paper_figures.py"]
DEPOSIT = ROOT / "tools" / "prepare_zenodo_deposit.py"

PATH_RE = re.compile(r'["\'](data/[A-Za-z0-9_./-]+\.(?:csv|json|jsonl))["\']')


def generator_inputs() -> set[str]:
    found = set()
    for g in GENERATORS:
        p = ROOT / g
        if p.exists():
            found |= set(PATH_RE.findall(p.read_text(encoding="utf-8")))
    return found


def deposit_covers(rel: str, deposit_src: str) -> bool:
    """A file is covered if it is named, or if one of its ancestor directories is
    named as a tree. Substring matching on the basename alone would call
    `cells_P1.csv` covered by a comment that merely mentions it."""
    if f'"{rel}"' in deposit_src or f"'{rel}'" in deposit_src:
        return True
    parts = rel.split("/")
    for i in range(len(parts) - 1, 0, -1):
        tree = "/".join(parts[:i])
        if f'"{tree}"' in deposit_src or f"'{tree}'" in deposit_src:
            return True
    return False


def main() -> int:
    if not DEPOSIT.exists():
        raise SystemExit(f"[deposit] missing {DEPOSIT.relative_to(ROOT)}")
    src = DEPOSIT.read_text(encoding="utf-8")
    inputs = sorted(generator_inputs())
    missing = [r for r in inputs if not deposit_covers(r, src)]

    print(f"generators read {len(inputs)} data files; "
          f"{len(inputs) - len(missing)} covered by the deposit\n")
    for rel in missing:
        on_disk = "exists" if (ROOT / rel).exists() else "ABSENT"
        print(f"   NOT DEPOSITED  {rel:44s} ({on_disk} locally)")
    if missing:
        print("\n[deposit] REFUSING: the data-availability statement promises "
              "every table and figure regenerates from the deposit, and these "
              "inputs are in no include or hash-only list. Deciding which may "
              "travel is a licence question, not a script's: see this file's "
              "docstring for what each one contains.")
        return 1
    print("[deposit] every generator input is covered")
    return 0


if __name__ == "__main__":
    sys.exit(main())
